import { type Metadata } from "next";
import { Providers } from "./providers"; // ClerkProvider shu yerga o'tdi
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import NavigationMenu from "@/components/NavigationMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16 border-b">
            <div className="flex gap-4">
              {/* Clerk SignIn & UserButton */}
            </div>
          </header>
          <NavBar />
          <NavigationMenu />
          <main className="p-4">{children}</main>
        </body>
      </html>
    </Providers>
  );
}
