import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import NavigationMenu from "@/components/NavigationMenu";
import Providers from "@/app/providers"; // Yaratilgan Providers fayli

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dokon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <div className="layout-container">
            <NavBar />
            <NavigationMenu />
            <main className="p-4 main-content">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
